_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 100

weights_summary: null
progress_bar_refresh_rate: 10

# resume_from_checkpoint: "E:/YandexDisk/Work/dnamvae/models/fcmlp_model/logs/runs/2021-06-09/01-45-07/checkpoints/epoch=223_fold_1.ckpt"
resume_from_checkpoint: null
